name: Trigger release on new Helm version
on:
  schedule:
    # Rebuild once a week
    - cron:  '0 0 * * 0'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Create tags
      id: create-tag
      run: |
        GHCR_IMAGE=ghcr.io/${{ github.repository_owner }}/texlive-full
        VERSION="$(date +'%Y-%m-%d')"
        TAGS="${GHCR_IMAGE}:latest,${GHCR_IMAGE}:${VERSION}"
        echo "TAGS=${TAGS}" | tee -a $GITHUB_ENV
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ env.TAGS }}
        labels: |
          org.opencontainers.image.authors=${{ github.repository_owner }}
          org.opencontainers.image.created=${{ env.BUILD_DATE }}
          org.opencontainers.image.description=Created from commit ${{ env.GIT_SHA }} and ref ${{ env.GIT_REF }}
          org.opencontainers.image.ref.name=${{ env.GIT_REF }}
          org.opencontainers.image.revision=${{ env.GIT_SHA }}
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.description=Created from commit ${{ env.GIT_SHA}} and ref ${{ env.GIT_REF }}
      